# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") || "root" %>
  password: <%= ENV.fetch("DB_PASSWORD") || "test" %>
  host: <%= ENV.fetch("DB_HOST") || "localhost" %>
  port: <%= ENV.fetch("DB_PORT") || 3306 %>
  database: <%= Rails.env.production? ? ENV.fetch("DB_NAME") : "#{ENV.fetch("DB_NAME")}_#{Rails.env}" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

